### ISSUE TITLE
does it work in 1.5.4 kade?

### ISSUE THREAD

**Issue by imdumlol** [TorchTheDragon/TorchFNFExperiments#1]

**Comment by TorchTheDragon** [comment]
It should, just follow the similar instructions to the BoloVEVO Kade, they should be similar enough

**Comment by imdumlol** [comment]
does it also work on psych 0.4.2?

**Comment by TorchTheDragon** [comment]
It should as the only editing to the main file is essentially adding a line to the menu you want to add it too

**Comment by imdumlol** [comment]
thx

**Comment by imdumlol** [comment]
what .hx file is it?

**Comment by TorchTheDragon** [comment]
Can you clarify that a little better? Like, do you mean which .hx file is the Character Menu or do you mean where do you put the additional line? If it is the second question, you just put it wherever you need it to be, so it can be in Freeplay.hx (as used in my example), MainMenuState.hx, or even PlayState.hx if you want, you just need something that'll force the state.

**Comment by imdumlol** [comment]
oh i ment like what .hx file for the character menu

**Comment by TorchTheDragon** [comment]
For Kade it is https://github.com/TorchTheDragon/CharMenu/blob/main/BoloVEVOKade/source/CharMenu.hx

(With the Kade one, you may have to change the "import Song.SongData" at the top to something like "import Song.SwagSong")

For Psych it is https://github.com/TorchTheDragon/CharMenu/blob/main/PsychEngine/source/CharMenu.hx

**Comment by imdumlol** [comment]
alright so......................... i added it to psych it just did not work (on modded 0.4.2)

**Comment by TorchTheDragon** [comment]
Have you added the switch state to another Menu?

**Comment by TorchTheDragon** [comment]
I would recommend looking at line [53](https://github.com/TorchTheDragon/CharMenu/blob/main/PsychEngine/source/FreeplayState.hx#L53) and lines [400](https://github.com/TorchTheDragon/CharMenu/blob/main/PsychEngine/source/FreeplayState.hx#L400) through [414](https://github.com/TorchTheDragon/CharMenu/blob/main/PsychEngine/source/FreeplayState.hx#L414)

These are from the FreeplayState.hx file

**Comment by TorchTheDragon** [comment]
Another thing that could help is this instructions page I have made: https://github.com/TorchTheDragon/CharMenu/tree/main/Instructions/Psych
