### ISSUE TITLE
Psych Engine 0.6.3 Android Port

### ISSUE THREAD

**Issue by InevitableFate** [TorchTheDragon/TorchFNFExperiments#2]
**What is the name of the Engine?**
Psych Engine

**Link to the source code of the Engine**
https://github.com/MaysLastPlays-FNF-Things/FNF-PsychEngine

**Comment by TorchTheDragon** [comment]
Hey for an update, it is taking me forever to figure out how to compile for android, I am having errors without any code changes. Hopefully I get it to compile soon lol.

**Comment by TorchTheDragon** [comment]
I got it to compile, however I am now stuck here as the video it redirects me to is unlisted. If you know what to do, let me know please.

![Screenshot_20230330-114654](https://user-images.githubusercontent.com/72819066/228892603-63751de9-614c-4d67-8ce7-89fb2d459763.png)

**Comment by TorchTheDragon** [comment]
Nevermind I got it

**Comment by TorchTheDragon** [comment]
Here ya go, it is finished.

https://github.com/TorchTheDragon/TorchFNFExperiments/releases/tag/CharMenu-PyschAndroid

Here is the part of the repo that it is in if you would like to try and implement it the way I did or if you just want to use my version.
https://github.com/TorchTheDragon/TorchFNFExperiments/tree/main/PsychEngine-Android
