### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by brusakas** [TorchTheDragon/TorchFNFExperiments#5]
**Describe the bug**
I followed your steps clearly and whenever i open to character menu it would say the error 'null object reference'.

**Where is the error?**
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 545
Called from flixel.FlxGame::step flixel/FlxGame.hx line 677
Called from flixel.FlxGame::update flixel/FlxGame.hx line 724
Called from flixel.FlxGame::switchState flixel/FlxGame.hx line 637
Called from CharMenu::create CharMenu.hx line 179
Called from Boyfriend::new Boyfriend.hx line 16
Called from Character::new Character.hx line 164
Called from flixel.graphics.frames.FlxAtlasFrames::fromSparrow flixel/graphics/frames/FlxAtlasFrames.hx line 250

**Expected behavior**
I expected for it to load into the charmenu state.

**Engine (please complete the following information):**
 I'm currently on PE 0.5.2h

**Comment by TorchTheDragon** [comment]
It may be different for the older psych engines, you will have to see the changes in the variables to try and figure out what has been changed. Currently, the last saved version I made works on 0.6.3, sorry.

**Comment by TorchTheDragon** [comment]
I am in the works for one to be done for 0.7.3

**Comment by brusakas** [comment]
hmm ok, final note: this piece of code in charmenu.hx was logged to be the culprit: var characterImage:Boyfriend = new Boyfriend(0, 0, unlockedCharacters[i]); 

boyfriend.hx - line 16 - super(x, y, char, true);

character.hx = line 164 -  case "sparrow":
						frames = Paths.getSparrowAtlas(json.image);

**Comment by brusakas** [comment]
nvm i fixed it
